apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/name: prometheus-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: prometheus
        app.kubernetes.io/name: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.51.2
          args:
            - "--config.file=/etc/prometheus/conf/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--storage.tsdb.retention.time=2d"
            - "--storage.tsdb.retention.size=0"
            - "--log.level=info"
            - "--log.format=logfmt"
            - "--web.listen-address=:9090"
            - "--web.console.libraries=/etc/prometheus/conf/console_libraries"
            - "--web.console.templates=/etc/prometheus/conf/consoles"
            - "--web.route-prefix=/"
          ports:
            - name: http
              containerPort: 9090
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
            httpGet:
              path: /-/healthy
              port: http
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
            httpGet:
              path: /-/ready
              port: http
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/conf
              readOnly: true
            # - name: prometheus-data
            #   mountPath: /prometheus/data
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-server-conf
        # - name: prometheus-data
        #   emptyDir: {}
